cors:
    originPatterns: http://localhost:8080,http://localhost:3000,https://effecta.com.br
spring:
    application:
        name: rest-with-spring-boot-and-java
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/rest_springboot_test?useTimezona=true&serverTimezone=UTC
        username: root
        password: 1234567
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
        show-sql: false
        open-in-view: true
logging:
    level:
        root: INFO
        br.com.effecta: INFO
spring-doc:
    paths-to-match: /api/**/v1/**
    swagger-ui:
        use-root-path: true